### ISSUE TITLE
filetime1, 2 기반 기술 조사

### ISSUE THREAD

**Issue by Ryeoly** [Hyunwoo-CHO/Project2#1]

**Comment by Ryeoly** [comment]
해더 파일 #include <time.h>를 이용해 시간 정보를 다룰 수 있도록 한다. 
해더 파일 #include <sys/stat.h>는 파일 정보를 위한 여러 함수들을 사용하기 위해 사용한다. 

localtime_r 함수는 time_t type의 초단위 시간을 지역 시간의 struct tm type으로 변환하는 함수입니다. 
첫번째 인자는 마지막 수정시간, 최근 access, create time 등 파일의 상태를 나타내고
두번째 인자는 첫번째 인자의 상태를 받아 struct tm을 나타내게 됩니다. 

time1, 2는 각 파일에 해당하는 struct tm 값을 가져야 하기 때문에 동적할당을 사용해 time1, 2를  선언해줍니다.

**Comment by dtree0520** [comment]
확인이요. 잘 이해하였습니다.

**Comment by starz-woo** [comment]
확인했습니다.
