### ISSUE TITLE
datecmp 기반 기술 조사

### ISSUE THREAD

**Issue by starz-woo** [Hyunwoo-CHO/Project2#15]

**Comment by starz-woo** [comment]
파일 수정 날짜의 정보를 가져오기 위해 tm 구조체의 tm_mon과 tm_mday 값을 사용한다.
tm_mon의 경우 1 ~ 12가 아닌 0 ~ 11로 나오기때문에 +1을 하여 월을 계산한다.
두 파일의 tm_mon과 tm_mday 각각의 차이를 통해 파일의 날짜를 비교한다.

**Comment by Ryeoly** [comment]
확인했습니다.
