### ISSUE TITLE
filestat 기반 기술 조사

### ISSUE THREAD

**Issue by starz-woo** [Hyunwoo-CHO/Project2#7]

**Comment by starz-woo** [comment]
struct stat 구조체와 int stat 함수를 사용하기 위해 sys/stat.h 헤더파일을 선언한다. 
파일의 정보가 들어가는 구조체 struct stat에는 ID of device containing file, inode number, protection, number of hard links, user ID of owner, group ID of owner, device ID의 정보가 저장된다. 
int stat(const char* path, struct stat* buf) 함수를 사용하여 struct stat 구조체 포인터 buf에해당 파일의 정보를 받아온다. int stat 함수의 인자로는 파일의 경로와 구조체 포인터가 사용된다.

**Comment by Ryeoly** [comment]
좋은 정보 공유 감사합니다.

**Comment by dtree0520** [comment]
네 확인이요

**Comment by starz-woo** [comment]
*추가 내용
struct stat 구조체 내에 total size(in bytes), block size for file system I/O, number of 512B blocks allocated, time of last access, time of last modification, time of last status change의 정보 또한 저장
