### ISSUE TITLE
timecmp 기반 기술 조사

### ISSUE THREAD

**Issue by Ryeoly** [Hyunwoo-CHO/Project2#8]

**Comment by Ryeoly** [comment]
timecmp 함수는 파일 두개의 마지막 수정 시간, 분을 비교하는 함수입니다. 

struct tm을 filetime1,2 함수에서 지정해주었으므로 tm에 접근하여 시간과 분을 받아냅니다. 

tm->hour는 시간, tm->min은 분을 나타냅니다. 이를 비교하는 조건문을 활용하여 compare해줍니다.

**Comment by dtree0520** [comment]
잘 이해하였습니다. 수고 많으십니다^^

**Comment by starz-woo** [comment]
이해했습니다
